
server:
  port: 8763

spring:
  application:
    name: test

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
 
#开启熔断器
feign:
  hystrix:
    enabled: true
