
server:
  port: 8764

spring:
  application:
    name: test
    
management:
   endpoints: 
     web:
       exposure: 
         include: hystrix.stream 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
